making pipeline generic

diff --git a/ci/pipelines/load-tile-stage-configure.yml b/ci/pipelines/load-tile-stage-configure.yml
--- a/ci/pipelines/load-tile-stage-configure.yml
+++ b/ci/pipelines/load-tile-stage-configure.yml
@@ -26,9 +26,8 @@ resources:
     owner: haydonryan
     repository: ((github_repository_name))
     access_token: ((github_access_token))
-  
 
-- name: p-mysql
+- name: ((product-name))
   type: pivnet
   source:
     api_token: ((pivnet-api-token))
@@ -61,8 +60,8 @@ jobs:
   - get: source
     trigger: true
     passed: [upload]
-  - get: state
-  - get: tile-configurator
+  
+
   - task: fetch-binary
     config:
       platform: linux
@@ -70,9 +69,8 @@ jobs:
         type: docker-image
         source: { repository: czero/cflinuxfs2 }
       inputs:
-      - name: state
       - name: source
-      - name: tile-configurator
+
         #outputs:
         #- name: nexus-artifact-shasum
       run:
@@ -119,7 +117,7 @@ jobs:
           set -e
           set -x
           echo Setting Network the old way as we do not support setting this... yet.....
-          om-linux -k -u ((opsman_admin_username)) -p ((opsman_admin_password)) -t ((opsman_domain_or_ip_address)) configure-product --product-name ((product-name)) -pn '{"network":{"name":"DEPLOYMENT"},"other_availability_zones":[{"name":"PCF Cluster"}],"singleton_availability_zone":{"name":"PCF Cluster"}}'
+          om-linux -k -u ((opsman_admin_username)) -p ((opsman_admin_password)) -t ((opsman_domain_or_ip_address)) configure-product --product-name ((product-name)) -pn ((networks))
 
   - task: configure-product
     config:
@@ -142,11 +140,36 @@ jobs:
           set -x
           cp source/help.yml .                                  # these need to be in the current directory -
           cp source/dictionary.yml .                            # to assist with convertinggit 
+          if [ ! -f state/((config-file)) ]; then
+          echo "Configuration file (((config-file))) not found in your configuration repository!"
+          exit 1
+          fi
           chmod +x tile-configurator/tile-configurator-linux    # make this executable
-          #tile-configurator/tile-configurator-linux --help
-          tile-configurator/tile-configurator-linux config --url=((opsman_domain_or_ip_address)) -u ((opsman_admin_username)) -p ((opsman_admin_password)) -i state/mysql.yml -t ((product-name))
+          tile-configurator/tile-configurator-linux config --url=((opsman_domain_or_ip_address)) \
+            -u ((opsman_admin_username)) -p ((opsman_admin_password)) -i state/((config-file)) -t ((product-name))
 
-
+- name: apply-changes
+  plan:
+  - get: source
+    trigger: true
+    passed: [configure]
+  - task: apply-changes
+    config:
+      platform: linux
+      image_resource:
+        type: docker-image
+        source: { repository: czero/cflinuxfs2 }
+      inputs:
+      - name: state
+        #outputs:
+        #- name: nexus-artifact-shasum
+      run:
+        path: bash
+        args:
+        - -c
+        - |
+          set -ex
+          echo applying changes
 # get tile from pivnet
 
 # upload tile to ops manager
